// Thin Supabase access for tasks, sessions and work hours. Every failure throws so the screen can show it.
import { supabase } from "./supabase";
import type { NewTask, Task, TaskEdit, TaskType, ConditionPlace, Priority } from "./tasks";
import type { WorkHours } from "./scheduler";
import { DEFAULT_WORK_HOURS } from "./scheduler";

interface TaskRow {
  id: string;
  title: string;
  type: TaskType;
  duration_min: number;
  topic: string | null;
  deadline: string | null;
  spread_days: number | null;
  condition_place: ConditionPlace;
  held: boolean;
  unplaced: boolean;
  done: boolean;
  priority: Priority;
}

interface SessionRow {
  id: string;
  task_id: string;
  start_at: string;
  end_at: string;
  calendar_event_id: string | null;
}

export interface StoredSession {
  id: string;
  taskId: string;
  start: number;
  end: number;
  calendarEventId: string | null;
}

export interface NewSession {
  id: string; // generated by the app, so the calendar event can link to it before the row exists
  taskId: string;
  start: number;
  end: number;
  calendarEventId: string | null; // null for Work day sessions, which have no event
}

function client() {
  if (!supabase) throw new Error("Supabase is not configured.");
  return supabase;
}

function fromRow(row: TaskRow): Task {
  return {
    id: row.id,
    title: row.title,
    type: row.type,
    durationMin: row.duration_min,
    topic: row.topic,
    deadline: row.deadline,
    spreadDays: row.spread_days,
    conditionPlace: row.condition_place,
    held: row.held,
    unplaced: row.unplaced,
    done: row.done,
    priority: row.priority,
  };
}

function check<T>(result: { data: T | null; error: { message: string } | null }): T {
  if (result.error) throw new Error(result.error.message);
  if (result.data === null) throw new Error("No data returned.");
  return result.data;
}

export async function listTasks(): Promise<Task[]> {
  const result = await client().from("tasks").select("*").order("created_at", { ascending: true });
  return check<TaskRow[]>(result).map(fromRow);
}

export async function insertTask(task: NewTask): Promise<void> {
  const row = {
    title: task.title,
    type: task.type,
    duration_min: task.durationMin,
    topic: task.topic,
    deadline: task.deadline,
    spread_days: task.spreadDays,
    condition_place: task.conditionPlace,
  };
  check(await client().from("tasks").insert(row).select());
}

export async function updateTaskEdit(id: string, edit: TaskEdit): Promise<void> {
  const row = { title: edit.title, duration_min: edit.durationMin, deadline: edit.deadline, priority: edit.priority };
  check(await client().from("tasks").update(row).eq("id", id).select());
}

// Marks the task done or not done (SPEC 2.7). Done tasks are never placed.
export async function setDone(id: string, done: boolean): Promise<void> {
  check(await client().from("tasks").update({ done }).eq("id", id).select());
}

// Drag between priority sections changes only the priority (SPEC 2.7).
export async function setPriority(id: string, priority: Priority): Promise<void> {
  check(await client().from("tasks").update({ priority }).eq("id", id).select());
}

// Holds the task out of automatic placement (SPEC 2.5) and removes its sessions.
// The hold is saved first: if the session delete fails, the task is still held and the error is shown.
export async function holdTask(id: string): Promise<void> {
  check(await client().from("tasks").update({ held: true }).eq("id", id).select());
  const result = await client().from("sessions").delete().eq("task_id", id);
  if (result.error) throw new Error(result.error.message);
}

// A "Schedule" action: releases the hold so the next placement run can place the task (SPEC 2.5).
export async function releaseHold(id: string): Promise<void> {
  check(await client().from("tasks").update({ held: false }).eq("id", id).select());
}

export async function deleteTask(id: string): Promise<void> {
  const result = await client().from("tasks").delete().eq("id", id);
  if (result.error) throw new Error(result.error.message);
}

export async function listSessions(): Promise<StoredSession[]> {
  const result = await client().from("sessions").select("*").order("start_at", { ascending: true });
  return check<SessionRow[]>(result).map((row) => ({
    id: row.id,
    taskId: row.task_id,
    start: Date.parse(row.start_at),
    end: Date.parse(row.end_at),
    calendarEventId: row.calendar_event_id,
  }));
}

export async function insertSessions(sessions: NewSession[]): Promise<void> {
  const rows = sessions.map((p) => ({
    id: p.id,
    task_id: p.taskId,
    start_at: new Date(p.start).toISOString(),
    end_at: new Date(p.end).toISOString(),
    calendar_event_id: p.calendarEventId,
  }));
  check(await client().from("sessions").insert(rows).select());
}

export async function moveSession(id: string, start: number, end: number): Promise<void> {
  const row = { start_at: new Date(start).toISOString(), end_at: new Date(end).toISOString() };
  check(await client().from("sessions").update(row).eq("id", id).select());
}

// Work hours (SPEC 2.4). With no saved row, the defaults apply.
export async function getWorkHours(): Promise<WorkHours> {
  const rows = check<{ start_min: number; end_min: number; lunch_start_min: number; lunch_end_min: number }[]>(
    await client().from("work_settings").select("start_min, end_min, lunch_start_min, lunch_end_min"),
  );
  const row = rows[0];
  return row
    ? { startMin: row.start_min, endMin: row.end_min, lunchStartMin: row.lunch_start_min, lunchEndMin: row.lunch_end_min }
    : DEFAULT_WORK_HOURS;
}

export async function saveWorkHours(hours: WorkHours): Promise<void> {
  const row = { start_min: hours.startMin, end_min: hours.endMin, lunch_start_min: hours.lunchStartMin, lunch_end_min: hours.lunchEndMin };
  check(await client().from("work_settings").upsert(row, { onConflict: "owner_id" }).select());
}

// Deletes the task's sessions. Used when a placed task is edited, so the next placement run places it again (SPEC 2.5).
export async function deleteSessionsOf(id: string): Promise<void> {
  const result = await client().from("sessions").delete().eq("task_id", id);
  if (result.error) throw new Error(result.error.message);
}

// Sets the unplaced flag for these tasks (SPEC 5). Only the tasks whose flag changed are sent.
export async function setUnplaced(ids: string[], unplaced: boolean): Promise<void> {
  if (ids.length === 0) return;
  check(await client().from("tasks").update({ unplaced }).in("id", ids).select());
}
